[project]
name = "todo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "twpro8", email = "twpro8@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.1",
    "uvicorn>=0.40.0",
]

[project.scripts]
todo = "todo:main"

[build-system]
requires = ["uv_build>=0.8.5,<0.9.0"]
build-backend = "uv_build"
